### ISSUE TITLE
Vite: <file> has no corresponding SFC entry in the cache

### ISSUE THREAD

**Issue by chriscalo** [chriscalo/vite-multipage#1]
Tried to build & run:
``` sh
yarn build && yarn start
```

Output:
``` text
yarn run v1.22.10
warning package.json: No license field
$ vite build
building for production...
[vite:vue] /Users/ccalo/Projects/vite-multipage/style/style.scss has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.
file: /Users/ccalo/Projects/vite-multipage/style/style.scss?vue&type=style&index=0&src&lang.scss
error during build:
Error: /Users/ccalo/Projects/vite-multipage/style/style.scss has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.
    at getDescriptor (/Users/ccalo/Projects/vite-multipage/node_modules/@vitejs/plugin-vue/dist/index.js:4410:11)
    at Object.transform (/Users/ccalo/Projects/vite-multipage/node_modules/@vitejs/plugin-vue/dist/index.js:4990:28)
    at /Users/ccalo/Projects/vite-multipage/node_modules/rollup/dist/shared/rollup.js:18781:25
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chriscalo** [comment]
Awaiting next Vite release

**Comment by chriscalo** [comment]
Turns out the problem is still happening in dev mode
